# Generated by Django 3.2.10 on 2022-02-01 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='division',
            field=models.TextField(null=True),
        ),
    ]
