# Generated by Django 2.1.7 on 2021-07-19 05:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0010_auto_20190326_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='oicontestrank',
            name='last_submission',
            field=models.DateTimeField(default=datetime.datetime(9999, 12, 31, 0, 0)),
        ),
    ]
