# Generated by Django 3.2.7 on 2021-12-24 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20211223_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='team_members',
            field=models.JSONField(default=list),
        ),
    ]
