# Generated by Django 3.2.10 on 2022-02-01 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_userprofile_team_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='division',
            field=models.TextField(null=True),
        ),
    ]
