# Generated by Django 3.2.10 on 2022-02-22 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_userprofile_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='source',
            field=models.TextField(null=True),
        ),
    ]
