# Generated by Django 2.1.7 on 2021-07-19 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_userprofile_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='github',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='major',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='mood',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='school',
        ),
    ]
