# Generated by Django 3.2.7 on 2021-10-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0014_problem_share_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
